apiVersion: v1
kind: Service
metadata:
  name: vprodb ##Important to match application.properties
spec:
  type: ClusterIP
  selector:
    app: vprodb
  ports:
    - protocol: TCP
      port: 3306       # The port that the service will expose
      targetPort: vprodb-port # The port on the Pod that the service should forward to
