apiVersion: v1
kind: Service
metadata:
  name: vprocache01 ##Important to match application.properties
spec:
  type: ClusterIP
  selector:
    app: vpromc
  ports:
    - protocol: TCP
      port: 11211       # The port that the service will expose
      targetPort: memcached-port # The port on the Pod that the service should forward to
