apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromc-deployment
  labels:
    app: vpromc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpromc
  template:
    metadata:
      labels:
        app: vpromc
    spec:
      containers:
      - name: memcached
        image: memcached:latest
        ports:
          - name: memcached-port
            containerPort: 11211
          
