apiVersion: v1
kind: Service
metadata:
  name: vpromq01 #Important to match application.properties
spec:
  type: ClusterIP
  selector:
    app: vprormq
  ports:
    - protocol: TCP
      port: 15672      # The port that the service will expose
      targetPort: rabbitmq-port # The port on the Pod that the service should forward to
