apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb-deployment
  labels:
    app: vprodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: matespinetti/vprofiledb
        volumeMounts:
          - name: vpro-db-storage
            mountPath: /var/lib/mysql
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-pass
      initContainers:
      - name: init-vprodb
        image: busybox
        volumeMounts:
          - name: vpro-db-storage
            mountPath: /var/lib/mysql
        command: ["rm", "-rf", "/var/lib/mysql/lost+found"]
      volumes:
      - name: vpro-db-storage
        awsElasticBlockStore:
          volumeID: vol-0d27cb937f18d44cd
          fsType: ext4
      nodeSelector:
        zone: us-east-1a
